### ISSUE TITLE
can you derive the 'ungrammar' format from this 

### ISSUE THREAD

**Issue by f01dab1e** [noir-lang/parser-fuzzer#2]
Hello, is it possible to derive the ungrammar format from this? 

https://github.com/rust-analyzer/ungrammar

**Comment by pczarn** [comment]
@f01dab1e Yes, it is possible. We are already deriving Pest here -- for an example of deriving see `bnf_to_pest.py`.

ungrammar lacks a few minor features, which is likely to make deriving more difficult.

**Comment by pczarn** [comment]
I can make a derive for ungrammar if you're sure you need it.

**Comment by f01dab1e** [comment]
yes it would be nice. I want to try to write a lossless parser. for simple formatter implementations as @jfecher suggested

**Comment by pczarn** [comment]
@f01dab1e is ungrammar different from EBNF only because it preserves whitespace and comments? How does that work? I see nothing about whitespace or comments in the rust.ungram example.

No, I haven't seen nautilus, and after a brief look it seems to me it may support additional features that we don't need. Also, it might be that parser-fuzzer is already doing similar work with afl.

**Comment by f01dab1e** [comment]
Comments and whitespace are stored as tokens that can be accessed in the following way:

```rust
impl Iterator for DocCommentIter {
    type Item = Comment;

    fn next(&mut self) -> Option<Comment> {
        self.iter.find_map(|element: NodeOrToken<SyntaxNode, SyntaxToken>| {
            element.into_token().and_then(Comment::cast).filter(Comment::is_doc)
        })
    }
}
```

Ungrammar is likely used for generating structures for convenient interaction with a untyped CST.

The CST might look something like this:
```
SOURCE_FILE@0..9 
  FN@0..9
    COMMENT@0..5 "/// a"
    WHITESPACE@5..6 "\n"
    FN_KW@6..8 "fn"
    WHITESPACE@8..9 " "
    ERROR@9..9
```

But yes, it seems like this isn't described, and I see that ungrammar users hardcode which tokens to generate structures for.

**Comment by pczarn** [comment]
@f01dab1e hey, I finished the ungram for you.

The python3 script `bnf-to-ungram.py` in this repo generates `grammar.ungram` from `grammar.bnf`.

Will it work?

Keep in mind that `grammar.bnf` is now outdated after many corrections to the Pest file.

**Comment by pczarn** [comment]
It contains some negation, and you may have to replace it somehow.

**Comment by pczarn** [comment]
I will have to update bnf by comparing with Pest if this file doesn't work for you. Well, I will have to do it anyway.

**Comment by f01dab1e** [comment]
I get an error:
```
Error { message: "unexpected character: `~`", location: Some(Location { line: 70, column: 15 }) }'
```

**Comment by pczarn** [comment]
@f01dab1e fixed. You can try again.

**Comment by f01dab1e** [comment]
https://www.rustexplorer.com/b/75qwpa

**Comment by pczarn** [comment]
Looks like ungram supports `*` but not `+`. I will try to make a workaround tomorrow.

**Comment by pczarn** [comment]
@f01dab1e you will have to turn strings into some identifiers and give me the names, example from Rust.ungram:

```
Literal =
  Attr* value:(
    'int_number' | 'float_number'
  | 'string' | 'raw_string'
  | 'byte_string' | 'raw_byte_string'
  | 'true' | 'false'
  | 'char' | 'byte'
  )
```

**Comment by pczarn** [comment]
There is no `'"' (!'"' ANY)* '"'`, only `string`

**Comment by pczarn** [comment]
@f01dab1e the ungram seems to get parsed OK now

**Comment by f01dab1e** [comment]
Thank you. Let's close the issue.
